# Generated by Django 5.2.9 on 2026-03-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplied',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
