# Generated by Django 4.1.3 on 2026-05-06 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_app', '0001_initial'),
        ('recruiter_app', '0002_jobapplied_email_sent'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobapplied',
            unique_together={('job_detail', 'candidate')},
        ),
    ]
